version: '3'

services:
  web:
    build: {{ base_path }}/src
    command: gunicorn fake_rall.wsgi:application --bind 0.0.0.0:8000 --log-level debug
    volumes:
      - ./static:/static
      - ./settings.py:/app/fake_rall/local_settings.py

  nginx:
    image: nginx:latest
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - {{ nginx_sock_path | dirname }}:{{ nginx_sock_path | dirname }}
    depends_on:
      - web

